import Head from "next/head";
import { Header } from "../components";
import HomePage from "./HomePage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Deziner App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HomePage />
    </div>
  );
}
